- CODIGO/ProtocolCmdParse.bas
- CODIGO/frmPanelGm.frm
Changed the /BORRARPENA command to /MODIFICARPENA to reflect the real behavior of the command.
The other commands referenced on the ticket were working as intended.
closes #42
> GM's commands

- CODIGO/frmConnect.frm
after returning from the main window
just called to reload server list on frmConnect's Form_Activate event
> Server list was not reloading

- INIT/sinfo.dat
just to use the new server address and added a localhost one for convenience
> Updated sinfo.dat 

- CODIGO/TileEngine.bas
when we mouse over a player it displays a blue or red overlay over the char image depending of his criminal status
> Mouse over character colors

- CODIGO/General.bas
- CODIGO/TileEngine.bas
- CODIGO/clsGrapchicalInventory.cls
- CODIGO/mDx8_Engine.bas
Fixed Direct3D8 initial flag (Unused depth buffer, and discard mode prevent double buffering of the frame).
Fixed Direct3D8 nested BeginScene/EndScene, decoupled framebuffer's clear and present operation.
Removed unused specular vertex attribute.
> Fixed Fullscreen exception (#95).

- CODIGO/frmConnect.frm
Fixed repeated values in news after reload form
#105
> Fixed repeated values in news after reload form

- CODIGO/General.bas
There is some cases when we cannot update the server list from https protocol (ie Windows XP, or outdated IE version) So to avoid clean the file sinfo.ini we do a validation before write the file.
> File Sinfo.ini is empty when no https response.

- CODIGO/Declares.bas
- CODIGO/General.bas
- CODIGO/frmCambiaMotd.frm
- CODIGO/frmCharInfo.frm
- CODIGO/frmConnect.frm
- CODIGO/frmGuildMember.frm
- CODIGO/frmGuildNews.frm
- CODIGO/frmPeaceProp.frm
- CODIGO/frmScreenshots.frm
Deleted serversrecibidos.
Set CurServer when clicking on server list.
Delete unused code
> Keep selected Server

- CODIGO/Carteles.bas
- CODIGO/General.bas
- CODIGO/JSON.bas
- CODIGO/ProtocolCmdParse.bas
- CODIGO/cJSONScript.cls
- CODIGO/cStringBuilder.cls
- CODIGO/clsAudio.cls
- CODIGO/clsGuildDlg.cls
- CODIGO/frmBancoObj.frm
- CODIGO/frmCambiaMotd.frm
- CODIGO/frmCantidad.frm
- CODIGO/frmComerciarUsu.frm
- CODIGO/frmCommet.frm
- CODIGO/frmCrearPersonaje.frm
- CODIGO/frmCustomKeys.frm
- CODIGO/frmGuildDetails.frm
- CODIGO/frmGuildLeader.frm
- CODIGO/frmMain.frm
- CODIGO/frmParty.frm
- CODIGO/frmSkills3.frm
- CODIGO/frmSolicitud.frm
- CODIGO/frmTutorial.frm
- CODIGO/frmUserRequest.frm
- CODIGO/mDx8_Party.bas
- CODIGO/mDx8_Text.bas
- CODIGO/mPooChar.bas
- CODIGO/modCompression.bas
- CODIGO/modScreenCapture.bas
Encontré un articulo donde explica muy bien como optimizar los strings en VB6 [acá dejo el link](http://www.aivosto.com/articles/stringopt.html) y por lo que decidí aplicarlo a este proyecto.
No apliqué todo, faltan un montón de optimizaciones todavía. Yo solo hice lo mas fácil jaja
> Optimización de strings

- CODIGO/mDx8_Engine.bas
Read colors from colores.dat file instead of hardcode it
> Read colors from colores.dat file instead of hardcode it

- CODIGO/Declares.bas
- CODIGO/General.bas
- CODIGO/modPing.bas
- Client.vbp
- INIT/Config.ini
La idea de este aporte era obtener en milisegundos el tiempo que tarda en responder un servidor para saber la latencia.
Intente con hacer un Ping pero este metodo es algo "debil" ya que algunos server tienen deshabilitado la posibilidad de pingear. Si alguien tiene una mejor solucion a esto bienvenido sea, como por ejemplo de alguna forma re utilizar el comando /ping .
Agregada la funcion GetIPFromHostName para obtener la IP desde un hostname y asi poder obtener la localizacion de la misma y agregar el pais al titulo.
> Ping to server to get time response

- CODIGO/General.bas
- CODIGO/Resolution.bas
- CODIGO/frmCrearPersonaje.frm
This validations are not longer necessaries as we change the forms, now we don't use anymore character name to create an account and also frmCrearPersonaje.frm is not longer asking for email and passwords
Also changed weird characters in popup introduced in this PR https://github.com/ao-libre/ao-cliente/pull/146
> Deleted unnecesaries validations to create account and create character

- CODIGO/Declares.bas
- CODIGO/Protocol.bas
- CODIGO/ProtocolCmdParse.bas
- CODIGO/frmMain.frm
Esta es la parte del cliente.
Créditos a maTih.- de GS-Zone por este código.
Fuente: https://www.gs-zone.org/temas/nuevo-centinela.69676/
> Re-Implementado - Sistema de Auditoría por Centinelas

- CODIGO/Declares.bas
- CODIGO/General.bas
- CODIGO/Protocol.bas
- CODIGO/TCP.bas
- CODIGO/TileEngine.bas
- CODIGO/clsGrapchicalInventory.cls
- CODIGO/frmCarp.frm
- CODIGO/frmComerciar.frm
- CODIGO/frmComerciarUsu.frm
- CODIGO/frmCrearPersonaje.frm
- CODIGO/frmForo.frm
- CODIGO/frmHerrero.frm
- CODIGO/frmMain.frm
- CODIGO/frmPanelAccount.frm
- CODIGO/mDx8_Ambiente.bas
- CODIGO/mDx8_Dibujado.bas
- CODIGO/mDx8_Engine.bas
- CODIGO/mDx8_Luces.bas
- CODIGO/mDx8_Particulas.bas
- CODIGO/mDx8_Party.bas
- CODIGO/mDx8_Text.bas
- CODIGO/modPing.bas
- CODIGO/modScreenCapture.bas
> Optimización: Eliminadas declaraciones de variables sin usar.

- CODIGO/General.bas
- INIT/Config.ini
Por defecto, la busqueda de servidores esta ACTIVADA. Pero si querés jugar en LAN o simplemente estás testeando y no querés andar poniendo la IP todas las veces que abris el juego podés desactivarla desde el Config.ini de la carpeta INIT modificando el valor de `BuscarServidores`.
0 = Desactivado
1 = Activado
> Mejora: Elegir si querés buscar servidores del repositorio de GitHub o no.

- CODIGO/Protocol.bas
- CODIGO/ProtocolCmdParse.bas
- INIT/messages.txt
Para iniciar un CvC, click izquierdo al lider del clan y /CVC
Para aceptar el CvC, /ACVC
Para entrar al CvC, /IRCVC
> Implementación: Sistema de Duelo entre Clanes (CvC)

- CODIGO/Declares.bas
- CODIGO/General.bas
Testié logueando diferentes personajes tal y como Bassinger hizo (después de aplicar este parche) y no encontré ningún clon.
Gracias Yhunja por aportar la solución en #158 .
Fixes #158 .
> PARCHE: Solución al bug de clones.

- CODIGO/frmMain.frm
Mensaje de error nulo, cuando entra a ese flow la aplicacion crashea
Se obtiene correctamente el mensaje de error del json ahora.
> Fixed null error message

- CODIGO/frmConnect.frm
Changed links for wiki and rules
> Changed links for wiki and rules

- CODIGO/General.bas
- CODIGO/frmConnect.frm
- CODIGO/frmOldPersonaje.frm
- CODIGO/frmPasswd.frm
- INIT/Config.ini
Ahora la lista de servers de va actualizar correctamente al iniciar el juego
Se simplifico un poco el codigo
Se creo boton para refrescar lista de servers.
Se puso correctamente la version del juego
> Server List fixed and simplified - Added versionTagRelease on Render

- CODIGO/frmCargando.frm
Me olvide de poner un exit function en caso de que todo estuviera bien, ahora no tira mas el falso error.
> Fixed End Function when there is no internet

- CODIGO/General.bas
Parche rapido para evitar errores en caso que no haya un mundo seleccionado.
Se tiene que mejorar esto.
> Added Alkon map as default, needs to be improved

- Lenguajes/english.json
- Lenguajes/spanish.json
Al hacer click sobre las coordenadas el juego explota por que no tiene los parametros de colores en el json
Ahora funciona bien.
> Al hacer click sobre las coordenadas el juego explota por que no tiene los parametros de colores en el json

- Lenguajes/spanish.json
Modifiqué algunas cosas que estaban mal escritas así como errores de ortografía o palabras que hacen que las frases no tengan mucho sentido.
> Propuesta de cambio

- CODIGO/General.bas
- CODIGO/Resolution.bas
- Ya no se actualiza la pantalla cuando elegis jugar en modo ventana.
- Se resetea la resolucion al cerrar desde el `Sub CloseClient()`.
> Arreglado: Cambio de resolución.

- CODIGO/ProtocolCmdParse.bas
El chequeo de GM's que viene incorporado es una chota. Sale rollback.
> Fix comando /BUSCAR

- CODIGO/Protocol.bas
- CODIGO/TCP.bas
- CODIGO/frmConnect.frm
- CODIGO/frmCrearCuenta.frm
- CODIGO/frmCrearPersonaje.frm
- CODIGO/frmMain.frm
- Todo el comportamiento relacionado con la apertura de Sockets o Winsocks y su conexión con el servidor fue encapsulada en un solo procedimiento.
- Arreglé el error al crear un PJ que te mandaba al frmPanelAccount.
- Al clickear "Crear Cuenta", primero se conecta con el servidor y después de abre el formulario.
- Saqué la re-conexión con el servidor completamente al pedo que se hacia en el frmCrearPersonaje.
Testeado y Funcional.
> Mejora y Arreglos en la conexión con el servidor.

- CODIGO/Declares.bas
- CODIGO/General.bas
- CODIGO/frmCrearPersonaje.frm
Added Nemauhak in the list of cities when we create a character, Hide the rest of the cities
> Se eliminaron todas las ciudades del dropdown en crear personaje, se dejo solo Nemahuak

- CODIGO/Declares.bas
- CODIGO/General.bas
- CODIGO/frmCrearPersonaje.frm
Me arrepenti de este cambio ya que al sacarlo no me di cuenta que el hogar SI se sigue utilizando, aunque los nuevos personajes nacen en nemahuak
> Revert "Se eliminaron todas las ciudades del dropdown en crear personaje, se dejo solo Nemahuak"

- CODIGO/General.bas
- Lenguajes/spanish.json
Fixed starts on create character screen
> Fixed starts on create character screen

- CODIGO/Formularios/frmCargando.frm
- CODIGO/General.bas
- Client.vbp
Las borro porque acabo de probar el nuevo clsInet en un Windows 7 con Internet Explorer 8 y la nueva implementacion funciona perfectamente.
> Deleted wrong error handling code and validations.

- CODIGO/Motor/clsGrapchicalInventory.cls
- Changelog-client.txt
Ahora las flechas tambien muestran mas informacion
> Ahora las flechas tambien muestran mas informacion

- .github/ISSUE_TEMPLATE.md
- .github/config.yml
Se creo archivo para crear issues mas claros
Se creo archivo para que el bot interactue con los pull requests.
> Se creo archivo para crear issues mas claros

- INIT/sinfo.dat
> Agregado server de agonzgom

- .github/config.yml
Cambie imagenes que envie el bot en los mensajes por unas con el juego
> Cambie imagenes que envie el bot en los mensajes por unas con el juego

- CODIGO/Motor/mDx8_ParticulasVBGORE.bas
Changed some variables declarations after its type declaration, 
Added missing D3DXIMAGE_INFO_A type
Made Smaller Fixes
> VBGore Particles

- CODIGO/Formularios/frmBancoObj.frm
- Lenguajes/english.json
- Lenguajes/spanish.json
Este sera el primero de una coleccion de cambios que hice en el pasado pero no subi por que no tenia tiempo de testearlos.
Primero que nada se agregaron muchisimos valores a `spanish.json` estos valores los tenia de antes en el branch `translate-interface` pero como el codigo ha ido evolucionando mientras tanto (se han agregado otros valores en los archivos en el transcurso del tiempo), cuidadosamente he revisado y 
agregado los nuevos que son los de formularios.
Se tradujeron estos nuevos valores y se agregaron al `english.json`, tambien arreglando algunos valores faltantes que no nos habiamos dado cuenta.
Una ves teniendo los 2 archivos con la misma cantidad de valores, pase a formatearlos con la siguiente herramienta: https://jsonformatter.org/json-pretty-print para tener ambos con el …
> Traduccion formularios - frmBancoObj.frm

- CODIGO/Formularios/frmMain.frm
Added function LoadTextsForm to maintain coherence to the rest of the app with the load of texts
Added translation to hardcoded text"
> Added function LoadTextsForm to maintain coherence to the rest of the app with the load of texts

- CODIGO/Formularios/frmConnect.frm
- Changelog-client.txt
Se arreglo el chkRecordar usuario, ahora no hace falta clickearlo para que funcione, si esta checkeado re-escribe el contenido en el config.ini como deberia ser, se agregaron un par de funciones para normalizar el form con el resto
> frmConnect.frm se aprolijo y se arreglo el chkRecordar usuario

- CODIGO/Formularios/frmCerrar.frm
- Changelog-client.txt
frmCerrar LoadFormTexts method created to maintain coherence with the rest of the forms
> frmCerrar LoadFormTexts method created to maintain coherence with the rest of the forms

- CODIGO/Motor/clsGrapchicalInventory.cls
- Changelog-client.txt
Ahora mostramos informacion de defensa de los cascos en el inventario
>  Ahora mostramos informacion de defensa de los cascos en el inventario 

- CODIGO/Formularios/frmCrearCuenta.frm
Added LoadTextForms to maintain coherence between forms
> Added LoadTextForms to maintain coherence between forms

- CODIGO/Aplicacion/ProtocolCmdParse.bas
- CODIGO/Red/Protocol.bas
- Changelog-client.txt
Added functionality to send message to the discord chat
> Added functionality to send message to the discord chat

- CODIGO/Red/Protocol.bas
Changed colors for some actions
pd: el bug que hay en la imagen del color del crimi con el ciudadano ya fue arreglado :)
> Changed colors for some actions

- CODIGO/Formularios/frmMain.frm
- CODIGO/General.bas
> Deleted some unused functions

- INIT/CharInfo.dat
Fixed modifier on frmCrearPersonaje with MODDANOARMAS and MODDANOPROYECTILES
> Fixed modifier on frmCrearPersonaje with MODDANOARMAS and MODDANOPROYECTILES

- CODIGO/Areas/TileEngine.bas
- CODIGO/Motor/clsBatch.cls
Gracias a Dr. Miqueas150 por la mejora en el manejo de Alpha y Angle.
Gracias a @FrankoH298  por el fix de renderizado de sprites.
Testeado (en el mapa Prision y en las coordenadas [195 53 53](https://github.com/ao-libre/ao-server/issues/198)) y Funcional!
Fixes [#198](https://github.com/ao-libre/ao-server/issues/198)
> Arreglados los errores de renderizado del SpriteBatch.

- CODIGO/Formularios/frmBuscar.frm
- Changelog-client.txt
- Lenguajes/english.json
- Lenguajes/spanish.json
Verifico que se haya seleccionado un item antes de crearlo en el formulario buscar para evitar un error que hace que se cierre el juego
>  Verifico que se haya seleccionado un item antes de crearlo en el formulario buscar para evitar un error que hace que se cierre el juego

- CODIGO/Declares.bas
Se cambia el valor de MAX_INVENTORY_SLOTS para que este acorde al server y se pueda juntar oro
> Se cambia el valor de MAX_INVENTORY_SLOTS para que este acorde al server y se pueda juntar oro

- CODIGO/Formularios/frmMain.frm
Validacion para cuando hago doble click en un slot vacio del inventario no se cierre el juego
>  Validacion para cuando hago doble click en un slot vacio del inventario no se cierre el juego

- CODIGO/Formularios/frmMain.frm
- CODIGO/General.bas
- CODIGO/Red/Protocol.bas
- Changelog-client.txt
Changed gold color for the frmMain and refactor how we calculate it
> Changed gold color for the frmMain and refactor how we calculate it

- CODIGO/Red/Protocol.bas
En el servidor el paquete se llamaba: PalabrasMágicas
En el servidor el paquete se llamaba: DecirPalabrasMagicas.
Tambien saqué los paquetes `ShowBlacksmithForm` y `ShowCarpenterForm` y meto su comportamiento en los paquetes donde se solicitan los datos de los elementos crafteables al servidor.
> Arreglado paquete mal declarado. 

- CODIGO/Formularios/frmMain.frm
Se cambio un poco el estilo de la consola para escribir en el chat normal y de clanes
> Se cambio un poco el estilo de la consola para escribir en el chat normal y de clanes

- CODIGO/Formularios/frmMain.frm
- CODIGO/Red/Protocol.bas
El chat de npcs tambien se muestra en consola de forma prolija
> wip - El chat de npcs tambien se muestra en consola de forma prolija

- CODIGO/Declares.bas
- CODIGO/Formularios/frmMain.frm
- CODIGO/Red/Protocol.bas
Ahora el servidor envia el nivel maximo del server y se arreglo la barra de experiencia para que cuando seamos lvl max este siempre completa
> Ahora el servidor envia el nivel maximo del server y se arreglo la barra de experiencia para que cuando seamos lvl max este siempre completa

- CODIGO/Areas/TileEngine.bas
- CODIGO/Motor/mDx8_Engine.bas
> Sacados del main loop la creacion de los colores para invi y paralisis

- CODIGO/Areas/TileEngine.bas
- CODIGO/General.bas
- CODIGO/Motor/mDx8_Dibujado.bas
- CODIGO/Motor/mDx8_Engine.bas
- CODIGO/Motor/mDx8_Utilidades.bas
- CODIGO/Red/Protocol.bas
- Client.vbp
Separo en 2 funciones los Subs que son claves para el motor grafico de los que no lo son.
> Reorganizo el codigo un poco.

- CODIGO/Red/Protocol.bas
El juego esta roto y estoy tratando de entneder q pasa
se mandan un monton de veces el paquete 23 cuando me conecto y para verlo mas facil los indices
> Se agrego numero identificador al enum del serverpacketid

- CODIGO/Formularios/frmMain.frm
- CODIGO/Red/Protocol.bas
Cambios en los paquetes de actualizar inventarios del user, npc y bóveda.
PD: No deja mergear automáticamente, seguro por los paquetes que borré del ServerPacketID
> Nuevo fix al bug de spamear al comprar + revierto codigo en DataArrival

- CODIGO/Declares.bas
- CODIGO/Motor/mDx8_Dibujado.bas
- CODIGO/Red/Protocol.bas
Panel de cuenta:
Ahora se dibujan en la posición correcta los cascos y sombreros.
Ahora se dibujan los caspers como deben.
> Fixed cascos y caspers en panel de cuenta

- CODIGO/Formularios/frmCrearPersonaje.frm
> Fixed cabezas enanos/gnomos en crear personaje

- CODIGO/IO/modCarga.bas
Agregados los casteos de string a números correspondientes, sino tira que no coinciden los tipos.
> Fixed carga de hechizos

- CODIGO/Formularios/frmConnect.frm
- CODIGO/Red/Protocol.bas
Agregados valores fijos al enum serverpacketid, fix en frmConnect con Remember password
> Agregados valores fijos al enum serverpacketid, fix en frmConnect con Remember password

- CODIGO/Formularios/frmMain.frm
Se elimina el icono por que algunos les tira error 500003, hay que buscar el icono viejo y ponerlo
> Se elimina el icono por que algunos les tira error 500003, hay que buscar el icono viejo y ponerlo

- CODIGO/Areas/TileEngine.bas
Sí, ya sé, un pixel solo. Pero se notaba.
> Fix personajes se dibujaban 1 pixel corridos

- CODIGO/Formularios/frmBuscar.frm
- CODIGO/General.bas
- CODIGO/Red/Protocol.bas
frmBuscar: autofoco, seleccionar con clic derecho y errHandling
> Mejoras frmBuscar y bugfix GuardarConfiguracion

- CODIGO/Red/Protocol.bas
Reimplemento esto, no recuerdo el PR.
Sólo funciona si también meten la parte del server.
> Reducidos paquetes de comercio y boveda

- CODIGO/Areas/TileEngine.bas
- CODIGO/Areas/mPooChar.bas
- CODIGO/Formularios/frmMain.frm
- CODIGO/General.bas
- CODIGO/Motor/mDx8_Dibujado.bas
- CODIGO/Motor/mDx8_Engine.bas
- CODIGO/Motor/mDx8_Text.bas
- CODIGO/Red/Protocol.bas
#457: Fix tiempo invisibilidad y paralizar
#463: Fix espada Mata Dragones, fix indicador del minimapa y relantizado el cartel de daño sobre Char
#464: Saco del mainloop la creación de colores para invisibilidad y paralizar
#465: Fix letras que tiemblan al moverse
#457 y #465 hechos por @FrankoH298 
Mergear junto con PR 368 en el server
> Reimplementados #463, #464, #465 y #457

- Client.vbp
> Fix: Agrego frmArtesano.frm al proyecto

- CODIGO/Formularios/frmPanelAccount.frm
- Lenguajes/english.json
- Lenguajes/spanish.json
Se tradujo el formulario frmPanelAccount completamente
> Se tradujo el formulario frmPanelAccount completamente

- CODIGO/Areas/TileEngine.bas
- CODIGO/General.bas
- Changelog-client.txt
Creditos a @abusiv0 por implementarlo, yo solo lo fixie.
> Reflejo del char cuando te acercas al agua.

- CODIGO/Formularios/frmPanelAccount.frm
- CODIGO/Red/Protocol.bas
Mergear https://github.com/ao-libre/ao-server/pull/383
> Arreglada vulnerabilidad que te permite borrar pj's ajenos.

- CODIGO/Formularios/frmListaAmigos.frm
- CODIGO/Formularios/frmMain.frm
- CODIGO/Red/Protocol.bas
- Client.vbp
habian algunos detalles que retocar
> Fix - Sistema de amigos.

- CODIGO/General.bas
- CODIGO/Red/Protocol.bas
Se comento dia y noche hasta que funcione bien
> Se comento dia y noche hasta que funcione bien

- CODIGO/Red/Protocol.bas
Fix #550: inventario no se actualiza al comprar/depositar
> Fix inventario no se actualiza

- CODIGO/Formularios/frmCrearPersonaje.frm
El function se llamaba asi mismo causando un Stack Overflow.
> Fix - Stack Overflow en frmCrearPersonaje.

- CODIGO/Areas/TileEngine.bas
- CODIGO/Formularios/frmCerrar.frm
- CODIGO/Formularios/frmMain.frm
- CODIGO/Motor/mDx8_Text.bas
- CODIGO/Red/Protocol.bas
Ahora cuando se deslogea, no cierra el socket sino que te lleva directamente a la pestaña de tu cuenta.
Se arreglo un bug con el alpha y los textos.
Ahora no deberia mostrar nunca numeros negativos en el tiempo restante de invisibilidad y paralisis, con timeGetTime en el servidor el numero se vuelve mas preciso.
> Arreglado reconectar al logear, y setAlpha() en drawText.

- CODIGO/Audio/clsAudio.cls
- CODIGO/Formularios/frmMain.frm
- CODIGO/Red/Protocol.bas
Arreglados errores en el frmMain, y ahora no se muestran textos vacios en consola.
> Fixes v0.13.28

- CODIGO/Areas/TileEngine.bas
- CODIGO/Areas/mPooMap.bas
- CODIGO/Declares.bas
- CODIGO/Formularios/frmMain.frm
- CODIGO/General.bas
- CODIGO/Motor/mDx8_Engine.bas
- CODIGO/Red/Protocol.bas
- Se arreglo la lista de hechizos (No la limpiaba cuando deslogeabamos).
- Cuando sos desmontado recibis el tiempo restante y lo mostras en el render.
- Se unifico los timers de tiempo restante de paralisis, invisibilidad y equitacion.
> Se dejaron totalmente funcionales las monturas

- CODIGO/Aplicacion/ProtocolCmdParse.bas
- CODIGO/Red/Protocol.bas
Esta muy mal hecho, genera clones, no andan los cofres, alta ver**
> Saco el evento Hunger Games alv.

- CODIGO/Areas/mPooMap.bas
Se le avisa al usuario que tiene que bajarse de la montura cuando va a ir bajo techo
> Se le avisa al usuario que tiene que bajarse de la montura cuando va a ir bajo techo

- CODIGO/Formularios/frmMain.frm
Se agrego flushbuffers a boton de skills y estadisticas por que sino el juego se cuelga
> Se agrego flushbuffers a boton de skills y estadisticas por que sino el juego se cuelga

- CODIGO/Areas/TileEngine.bas
- CODIGO/Areas/mPooChar.bas
- CODIGO/Red/Protocol.bas
Ahora sólo ves transparente a vos mismo y a los de tu clan
> Fix #591: ver otros usuarios invisibles

- CODIGO/Formularios/FrmRetos.frm
- CODIGO/Formularios/frmListaAmigos.frm
- CODIGO/Formularios/frmMain.frm
- CODIGO/Red/Protocol.bas
- Lenguajes/english.json
- Lenguajes/spanish.json
Se implemento traduccion en botones Retos y Amigos, se normalizo los nombres de los botones en el frmMain
Agregadas algunas traducciones en el frmRetos
Agregada traduccion faltante a boton salir de frmListaAmigos
Arreglo tambien este bug:
https://github.com/ao-libre/ao-cliente/issues/588
> Arreglo de traducciones en frmMain. frmRetos. frmListaAmigos, /hogar cancelado y Protocol.bas

- INIT/sinfo.dat
> Agrego server pruebas ledesma

- CODIGO/Areas/TileEngine.bas
- CODIGO/Areas/mPooChar.bas
- CODIGO/Red/Protocol.bas
Fix al cambiar de clan buguea el ver a otros invisibles.
Se ven los nombres cuando estás invisible:
> Mas fixes invi

- CODIGO/Red/Protocol.bas
- Changelog-client.txt
Saqué la parte del servidor xq daba problemas y decidí hacerlo todo client-side.
Testeado y funcional
> Cambiar personaje via /SALIR

- CODIGO/Areas/TileEngine.bas
- CODIGO/IO/modCarga.bas
Creditos a @Wyr0X por la implementación, yo solo hice el PR jaja.
Testeado y funcional..
Si deseas usar la carga de indices anterior:
- Descomentá [esta linea](https://github.com/ao-libre/ao-cliente/blob/2f114aace9c010f43ec26358b61b56dcd6587294/CODIGO/Areas/TileEngine.bas#L1044).
- Comentá o borrá [esta linea](https://github.com/ao-libre/ao-cliente/blob/2f114aace9c010f43ec26358b61b56dcd6587294/CODIGO/Areas/TileEngine.bas#L1043).
> Carga de indices desde Graficos.INI

- CODIGO/Aplicacion/Resolution.bas
Arreglo el problema de que si solo tengo Width o Heigth en 1024 o 768 no me deja cambiar la resolucion a pantalla completa .
> Arreglo el problema de que si solo tengo Width o Heigth en 1024 o 768 no me deja cambiar la resolucion a pantalla completa .

- CODIGO/Formularios/frmKeysConfigurationSelect.frm
- CODIGO/Formularios/frmtip.frm
Se arreglo seteo de valor en tooltip inicial y bug en modal para elegir preferencia de teclado
> Se arreglo seteo de valor en tooltip inicial y bug en modal para elegir preferencia de teclado

- CODIGO/Motor/mDx8_Luces.bas
> Parche luces

- CODIGO/Formularios/frmMain.frm
> Click minimapa

- CODIGO/Formularios/frmMapa.frm
- Lenguajes/english.json
- Lenguajes/spanish.json
Se tradujo el formulario frmMapa
> Se tradujo el formulario frmMapa

- CODIGO/Red/Protocol.bas
Gracias BelerianD por reportar y arreglar esto.
> Fix - Runtime al comerciar.

- CODIGO/Red/Protocol.bas
- Changelog-client.txt
Gracias BelerianD por reportar y arreglar el error.
> Ahora si, arreglo runtime al comerciar

- CODIGO/Formularios/frmCantidad.frm
Se agrando el ancho del label para que pueda entrar el texto Escriba la cantidad
> Se agrando el ancho del label para que pueda entrar el texto Escriba la cantidad

- Changelog-client.txt
- EXTRAS/Tutorial_spanish.dat
Eliminados acentos del tutorial ya que se veian mal en el juego por encoding
> Eliminados acentos del tutorial ya que se veian mal en el juego por encoding

- CODIGO/Formularios/frmMain.frm
Ahora las flechas se equipan con doble click y los arcos se pueden usar haciendo doble click
> Ahora las flechas se equipan con doble click y los arcos se pueden usar haciendo doble click

- CODIGO/Formularios/frmCargando.frm
Ahora dice que version tenemos y cual es la ultima version disponible cuando aparece el msgBox que dice que nuestra version no es la actual
> Ahora dice que version tenemos y cual es la ultima version disponible cuando aparece el msgBox que dice que nuestra version no es la actual

- CODIGO/Formularios/frmPanelGm.frm
error de texto en dos teclas del panel
> error de texto en dos teclas del panes

- CODIGO/Formularios/FrmRetos.frm
Con esto debería cargar los 1vs1, antes que los 2vs2 como antes.
> Arreglo, cargaba mal las opciones

- CODIGO/Formularios/frmPanelGm.frm
Invierto mapa seguro e inseguro estaba al revés.
> ReyarB invierto PK 0 y 1

- CODIGO/Formularios/frmMain.frm
> Fix #791: escribir mientras estás con /buscar

- CODIGO/Formularios/frmMain.frm
Corrijo la condición.
Nota: Lo de la consola transparente no cumple ninguna función con un fondo negro. Podría ponerse algo lindo de fondo
> Fix #790: mover la ventana

- CODIGO/Formularios/frmPanelGm.frm
Fix https://github.com/ao-libre/ao-server/issues/703
> Fix errata en PanelGM

- CODIGO/Formularios/frmPanelGm.frm
> Mas erratas en teclas

- INIT/fxs.ini
Fix en animación 47 para que quede acorde al PJ y pueda utilizarse para el /hogar.
> Fix en offsetY

- CODIGO/Areas/TileEngine.bas
Se nota mucho cuando ves la caminata re loca de los golems.
Gracias @guidota por el fix!
> Fix: Se veían la mitad de los frames en las animaciones.

- CODIGO/Aplicacion/ProtocolCmdParse.bas
Cuando escribo un comando estando muerto el juego tira error, lo arreglo
> Cuando escribo un comando estando muerto el juego tira error, lo arreglo

- CODIGO/Formularios/frmMain.frm
- CODIGO/Red/Protocol.bas
Agrego validacion para no enviar paquetes para mostrar ... cuando estoy invisible
> Agrego validacion para no enviar paquetes para mostrar ... cuando estoy invisible

- CODIGO/Formularios/frmMain.frm
- CODIGO/Motor/mDx8_Projectile.bas
- CODIGO/Red/Protocol.bas
Ahora me puedo equipar y desequipar mochilas con doble click y las cuchillas se pueden usar con doble click
> Ahora me puedo equipar y desequipar mochilas con doble click y las cuchillas se pueden usar con doble click

- CODIGO/Aplicacion/Resolution.bas
Ahora no se cierra el juego al tratar de mover la pantalla en fullscreen
> Ahora no se cierra el juego al tratar de mover la pantalla en fullscreen

- CODIGO/Areas/TileEngine.bas
- CODIGO/Areas/mPooMap.bas
- CODIGO/Red/Protocol.bas
- Lenguajes/spanish.json
Reverts ao-libre/ao-cliente#873
Revierto por que por algun motivo no compila jenkins, despues reviso.
> Revert " Ahora obtenemos el dato de ZONA en mapas para validar si caminar o no en dungeons."

- CODIGO/Areas/TileEngine.bas
- CODIGO/Areas/mPooMap.bas
- CODIGO/General.bas
- CODIGO/Red/Protocol.bas
- Lenguajes/spanish.json
Ahora si dejo andando bien el tema de monturas y dungeons
> Ahora si dejo andando bien el tema de monturas y dungeons

- INIT/sinfo.dat
Se arreglo el nombre del nuevo servidor latino, se acomodo la posición del servidor de Nati :)
> Actualizacion sinfo.dat

- INIT/sinfo.dat
> Actualizo mi sinfo

- CODIGO/Motor/mDx8_Engine.bas
> dejo menos transparencia de arboles

- CODIGO/Areas/TileEngine.bas
acorto distancia para dejar transparencia de arboles
> Cambio distancia de transparencia de arboles

- INIT/sinfo.dat
Se agrega nuevo server fácil en la lista de servers :)
> Actualización sinfo.dat

- INIT/sinfo.dat
Se agregó AOL Plus experiencia, oro y trabajo x50
> Actualizado sinfo.dat

- CODIGO/Declares.bas
- CODIGO/Formularios/frmPanelAccount.frm
- CODIGO/Motor/mDx8_Dibujado.bas
- CODIGO/Red/Protocol.bas
Corrección al problema de borrar PJ, que requería volver a iniciar sesión para ver el cambio. YA NO :)
> Borrar PJ no requiere reiniciar el cliente
