ao-libre/ao-cliente

- CODIGO/Declares.bas
- CODIGO/Protocol.bas
- CODIGO/ProtocolCmdParse.bas
- CODIGO/frmPanelGm.frm
/DE command has been created to delete tile exits, the user has to click on the tile with the tileExit to erase and then use the command /DE or by clicking on the /DE button in the GM panel.
> Destroy tile exit command

- CODIGO/General.bas
The ColoresPJ array was overriding index 50 (reserved for Red criminal color), with purple.
closes #62
> Criminal name was rendered in purple

- CODIGO/frmCargando.frm
- INIT/Config.ini
Changed parameter version for VersionTagRelease to maintain name normalization with the ao-server repository
> Changed parameter version for VersionTagRelease

- CODIGO/frmCrearPersonaje.frm
Parece que se podía crear un personaje dejando el campo "contraseña" y "confirmar contraseña" vacíos.
El chequeo del nickname (txtNombre) no puede faltar tampoco.
> Agregar chqeueos necesarios faltantes en el frmCrearPersonaje

- CODIGO/General.bas
- CODIGO/TileEngine.bas
- CODIGO/clsGrapchicalInventory.cls
- CODIGO/mDx8_Engine.bas
Should only be one BeginScene() and EndScene(), but requires to present each swapchain at the end of EndScene() and not within. There is a memory corruption somewhere related to Direct3D that corrupts everything (Once found, FVF_SPECULAR and Specular variable should be removed).
> Temporally fixed D3D memory corruption.

- CODIGO/General.bas
- CODIGO/clsByteBuffer.cls
Fuente: https://www.gs-zone.org/temas/carga-de-mapas-desde-la-memoria-cliente.91444/
Explicación (de 0xDEADBEEF):
> En vez de leer a trocitos el mapa de archivo, lo lee de golpe y lo mete en un buffer temporal. Luego ese buffer lo pasa de serial (un byte detrás de otro) a mapa, la estructura en memoria que define un mapa.
> 
> Esta operacion se hace de forma mas rapida que la anterior, esto se denomina batching (bueno no esto directamente, pero es el principio mas simple de esta técnica).
> 
> Batching es encapsular datos en bloque para no tener que operar muchas veces sobre ellos, o minizar operaciones costosas sobre estos. Mover todo el bloque de datos del mapa de archivo a memoria y luego operar desde memoria es mas eficiente que operar directamente desde archivo.
> Carga de mapas desde la memoria

- CODIGO/frmOpciones.frm
El imgRadio, lo borré.
El imgManual, te redirige al README.md.
El de imgSoporte, te redirige a la pestaña `Issues` de la repo.
Closes #64
> Parche: Eliminados links muertos frmOpciones

- CODIGO/General.bas
- CODIGO/mDx8_Minimap.bas
Cuando entrabas a un mapa que no tenia su .bmp en la carpeta "Graficos\MiniMapa", se cerraba el cliente.
> Fix: Mini-Mapa en Render con lectura de Imágenes.

- CODIGO/Declares.bas
- CODIGO/General.bas
- CODIGO/mDx8_Dibujado.bas
- Changelog-client.txt
- INIT/colores.dat
Ahora se renderiza:
- Cuando un user ATACA a un NPC y viceversa.
- Cuando un user CURA a un NPC o User y viceversa.
- Cuando un elemental ataca a un NPC o user y viceversa.
- Cuando un user FALLA un ataque a otro user o npc y viceversa.
- Cuando un user obtiene un objeto al trabajar. Aparece un "+1" arriba de tu cabeza.
- El mana recuperado al meditar. Aparece un "+valor recuperado" arriba de tu cabeza.
Los colores en los diferentes casos pueden cambiarse desde `colores.dat`
> Mejora - daño en render.

- CODIGO/General.bas
- CODIGO/TileEngine.bas
- CODIGO/mDx8_Dibujado.bas
Modifiqué principalmente el sub Damage_Draw. En ves de mantener un contador que avanza con cada frame utiliza la función GetTickCount (API de Windows) para obtener el tiempo REAL y que la animación sea estable a cualquier frame rate. Lo demás son cambios leves al posicionamiento del cartel y a la velocidad con la que sube.
> Texto del daño deja de depender de los FPS y se suavizó la animación

- CODIGO/TileEngine.bas
- CODIGO/mDx8_Text.bas
Demostración gráfica de los nombres corridos: [https://imgur.com/a/EtD1LcV](https://imgur.com/a/EtD1LcV)
Con respecto al otro bug, si creabas un personaje que incluya la palabra "XD" dibujaba un emoji en su lugar.
> Fix nombres descentrados + fix emojis en nombres

- CODIGO/Motor/clsSurfaceManDyn.cls
- CODIGO/Motor/clsSurfaceManStatic.cls
- Client.vbp
Este PR introduce la posibilidad de elegir entre cargar los gráficos comprimidos (Graphics.AO) o cargarlos directamente del archivo .PNG/.BMP en la carpeta `Graficos`.
Para alternar entre uno y otro deben modificar el flag de compilación `Compression` desde las propiedades del proyecto.
- `Compression = 0` para cargar los archivos descomprimidos.
- `Compression = 1` para cargar los gráficos desde Graphics.AO.
> Elegir carga de graficos con/sin compresión.

- CODIGO/Motor/mDx8_Engine.bas
Al inicializar el juego se declara si se usa vSync o no.
> Código inútil en Engine_FPS_Update()

- CODIGO/Formularios/frmBuscar.frm
- Changelog-client.txt
Chequeamos que la cantidad de items al crear un item en el frmBuscar sea menor o igual a MAX_INVENTORY_OBJS para evitar overflow
>  Chequeamos que la cantidad de items al crear un item en el frmBuscar sea menor o igual a MAX_INVENTORY_OBJS para evitar overflow

- CODIGO/Red/Protocol.bas
Según [este aporte](https://www.gs-zone.org/temas/las-consecuencias-de-usar-byte-en-handleincomingdata.99245) de Wolftein, hay un bug en el compilador de VB6 que hace que no se generen bien las tablas de salto en los bloques Switch, esto se arregla usando Integer o Long en este tipo de expresiones.
> Uso Long en la variable Packet del HandleIncomingData()

- CODIGO/Red/Protocol.bas
No se habia seteado el foco del formulario correctamente causando que al cargarse despues del frmMain se abriera en "segundo plano".
> El frmKeysConfigurationSelect se mostraba atrás del frmMain.

- CODIGO/Formularios/frmMain.frm
Bonus: el color del texto de ayuda es gris pero al empezar a escribir cambia al color original
> Ahora los textos de ayuda de las cajas de chat se van al escribir

- CODIGO/Formularios/frmBuscar.frm
- CODIGO/Red/Protocol.bas
- Lenguajes/english.json
- Lenguajes/spanish.json
Desde ya que no es mi intención menospreciar el trabajo de nadie ni mucho menos, pero me parecía que el formulario para buscar items y npcs se podía simplificar bastante. Dejé un único textbox para ingresar la búsqueda y una única lista para los resultados. Fiel a la idea original, con el clic derecho se abre un menú para crear los items o npc.
> Simplificado el uso del formulario /buscar

- CODIGO/Formularios/frmBuscar.frm
- CODIGO/Formularios/frmMain.frm
- CODIGO/General.bas
- CODIGO/Red/Protocol.bas
Todo lo que hice:
- Fix desbordamiento en frmBuscar con cantidades grandes
- Texto minimo para buscar reducido a 2 caracteres
- Ahora el frmBuscar tiene el foco al abrirse
- Fix al recibir muchos paquetes seguidos sobrepasa el buffer
- Fix guardar config antes de cargar los recursos del cliente
- Ahora con clic derecho seleccionas en la lista de frmBuscar
> Bugfixes frmBuscar y otros

- CODIGO/Formularios/frmCrearPersonaje.frm
... a veces. Esto pasaba porque picTemp.Width y picTemp.Height devuelven el tamaño total del PictureBox, contando los bordes. Al renderizar había lugares en los que los Grh se estiraban o comprimían por un pixel, produciendo imágenes distorsionadas.
> Personajes en frmCrearPersonaje se deformaban

- CODIGO/Red/Protocol.bas
Tiraba error si llegaban menos de 18 bytes, pero el paquete sólo necesita 17.
> Bufix paquete CharacterChange

- CODIGO/Red/Protocol.bas
Se remueve el dibujado de la cabeza en las barcas, galeras y galeones en el PannelAccount.
Solucionado así el siguiente commit: https://github.com/ao-libre/ao-cliente/issues/502
> Barca sin cabeza

- CODIGO/Formularios/frmConnect.frm
- Changelog-client.txt
- Lenguajes/english.json
- Lenguajes/spanish.json
Se agrego validacion para que en caso que no se pueda descargar la lista de servers de github, podamos usar la local y seguir usando el juego.
> Fix - Si no descarga la lista de servers de github arroja error y no deja usar mas el juego

- CODIGO/Declares.bas
El problema era que el MAXATRIBUTOS del cliente no coincidia con el del server. en consecuencia las funciones que controlaban el color del texto de la dopa daban error porque recibian valores mayores al esperado
> Fix al problema de las dopas

- CODIGO/Formularios/frmCrearPersonaje.frm
Al apretar `Volver` en el frmCrearPersonaje el timer que dibujaba la animación del Cuerpo del PJ seguía activado y seguía tratando de dibujar..
> Fix: No se detiene el timer del frmCrearPJ.

- CODIGO/Formularios/frmBancoObj.frm
Inspirado en minecraft, simple y comodo. Cuando apretas shift+click en un item deposita/extrae toda la cantidad de una. video demostrativo:
https://puu.sh/G8wOy.mp4
> Depositar/Retirar items rapido de la boveda con Shift+Click

- CODIGO/Red/Protocol.bas
Estaba mal el cálculo. Asumía que el gameTimer del server corre a 50ms, cuando en realidad corre a 40. También saqué el (-1) para que cuente desde la cantidad de segundos original hasta 1.
> Fix #788: timers de las dopas

- CODIGO/Motor/mDx8_Dibujado.bas
No sé por qué, pero la función pedía de parámetro un Byte, cuando debería ser Long
> Fix desbordamiento en Damage_NewSize

- CODIGO/Aplicacion/GameIni.bas
Cambio la carpeta para guardar videos a c:/videos por que no deja guardar los videos en la carpeta del juego por el UAC
> Cambio la carpeta para guardar videos a c:/videos por que no deja guardar los videos en la carpeta del juego por el UAC
